module.exports = {
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CHOOSE_CARD: "CHOOSE_CARD",
  FETCH_BOARD: "FETCH_BOARD",
  GENERATE_BOARD: "GENERATE_BOARD",
  SEND_PLAYER_INFO: "SEND_PLAYER_INFO",
  UPDATE_BOARD: "UPDATE_BOARD"
};
