module.exports = {
  CHAT_MESSAGE: "CHAT_MESSAGE",
  USER_NAME: "USER_NAME",
  CHOOSE_CARD: "CHOOSE_CARD",
  END_TURN: "END_TURN",
  GET_GAME: "GET_GAME",
  GET_PLAYER_INFO: "GET_PLAYER_INFO",
  FETCH_TEAMS: "FETCH_TEAMS",
  INDIVIDUAL_START_GAME: "INDIVIDUAL_START_GAME",
  JOIN_LOBBY: "JOIN_LOBBY",
  JOIN_SLOT: "JOIN_SLOT",
  REQUEST_INDIVIDUAL_START_GAME: "REQUEST_INDIVIDUAL_START_GAME",
  RESTART_GAME: "RESTART_GAME",
  START_GAME: "START_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  UPDATE_PLAYER_INFO: "UPDATE_PLAYER_INFO",
  UPDATE_TEAMS: "UPDATE_TEAMS"
};
