module.exports = {
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CHOOSE_CARD: "CHOOSE_CARD",
  GET_GAME: "GET_GAME",
  FETCH_TEAMS: "FETCH_TEAMS",
  INDVIDUAL_START_GAME: "INDVIDUAL_START_GAME",
  JOIN_LOBBY: "JOIN_LOBBY",
  JOIN_SLOT: "JOIN_SLOT",
  REQUEST_INDVIDUAL_START_GAME: "REQUEST_INDVIDUAL_START_GAME",
  RESTART_GAME: "RESTART_GAME",
  START_GAME: "START_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  UPDATE_TEAMS: "UPDATE_TEAMS"
};
